SNAPSHOT_TABLES = [
    "app_config",
    "alert_source",
    "channel",
    "channel_capability_tier",
    "channel_capability",
    "escalation_policy",
    "model_registry",
    "admin_unit",
    "unit_features",
    "safe_zone",
    "recipient",
    "relay_node",
    "incident",
    "alert",
    "alert_translation",
    "alert_approval",
    "alert_validation_result",
    "delivery",
    "delivery_event",
    "citizen_response",
    "assistance_case",
    "relay_confirmation",
    "audit_event",
    "reach_prediction",
]

SKIP_ROWS = {
    "admin_unit",
    "unit_features",
    "safe_zone",
    "channel_capability",
}

LOAD_ORDER = [
    "app_config",
    "alert_source",
    "channel",
    "channel_capability_tier",
    "escalation_policy",
    "model_registry",
    "recipient",
    "relay_node",
    "incident",
    "alert",
    "alert_translation",
    "alert_approval",
    "alert_validation_result",
    "delivery",
    "delivery_event",
    "citizen_response",
    "assistance_case",
    "relay_confirmation",
    "audit_event",
    "reach_prediction",
]
